Adding 10 open source blockchain projects to contribute to
commclassroom/roadmaps pull request #118
Opened 2022-08-16 16:38 UTC by SaadAnsari17

2022-08-18 07:44 UTC, kaiwalyakoparkar requested changes

2022-08-18 07:44 UTC, kaiwalyakoparkar commented on Blockchain/Contribute/README.md
> +-[Aelf](https://github.com/AElfProject/AElf)
Please add space between - and [...]
```diff
- -[Aelf]
+ - [Aelf]
```

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-18 07:44 UTC, kaiwalyakoparkar commented on Blockchain/Contribute/README.md
>  ## Open Source Projects you can contribute to
Add a blank line below the title text

2022-08-18 11:37 UTC, SaadAnsari17 commented on Blockchain/Contribute/README.md
>  ## Open Source Projects you can contribute to
Done👍

2022-08-19 08:33 UTC, kaiwalyakoparkar approved these changes
lgtm

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-08-19 08:33 UTC, merged