Adding up-for-grabs website and github in open source projects.
commclassroom/roadmaps pull request #193
Opened 2022-09-30 12:28 UTC by SaadAnsari17

## Fixes Issue

## Changes proposed

## Screenshots

## Note to reviewers

2022-09-30 15:27 UTC, kaiwalyakoparkar requested changes

2022-09-30 15:27 UTC, kaiwalyakoparkar commented on Open-Source/Contribute/Readme.md
> +- [up-for-grabs (Website)](https://up-for-grabs.net/#/)
Please remove the website. Only GitHub links are expected here

2022-09-30 15:55 UTC, SaadAnsari17 commented
Done

2022-10-01 06:17 UTC, kaiwalyakoparkar approved these changes
lgtm

2022-10-01 06:18 UTC, merged