Add Readme for frontend roadmap
commclassroom/roadmaps pull request #206
Opened 2022-10-09 19:28 UTC by vasucp1207

Take a look at the readme and please provide me feedback on what can I improve more.

2022-10-09 19:53 UTC, siddhant-khisty commented
@vasucp1207 Why are there 305 files? only one file had to be added

2022-10-09 19:55 UTC, vasucp1207 commented
@siddhant-khisty, they all are in .history folder

2022-10-09 20:01 UTC, siddhant-khisty commented
@vasucp1207 I'm not sure how a history folder was created, but please delete it. This PR should only add a `roadmap.md` to the Frontend-Roadmap folder

2022-10-09 20:05 UTC, vasucp1207 commented
Hey, @siddhant-khisty sorry for that I delete the .history folder

2022-10-09 20:12 UTC, siddhant-khisty requested changes

2022-10-09 20:12 UTC, siddhant-khisty commented on Frontend-Development/roadmap.md
> +#Frontend Roadmap
Add spaces between every heading for better readability

2022-10-09 20:12 UTC, siddhant-khisty commented on Frontend-Development/roadmap.md
> +### PWA
Remove line 113 as it is not required. Only keep the resources

2022-10-09 20:13 UTC, vasucp1207 commented
I think we should give it the name README.md not something like roadmap.md because this is not shown by default in the roadmap folder.

2022-10-10 04:41 UTC, kaiwalyakoparkar commented
> I think we should give it the name README.md not something like roadmap.md because this is not shown by default in the roadmap folder.

Hmm.. nice idea, let's do that

2022-10-10 08:12 UTC, vasucp1207 commented
@kaiwalyakoparkar, yeah I do that.

2022-10-10 08:29 UTC, siddhant-khisty approved these changes
LGTM

2022-10-10 13:42 UTC, kaiwalyakoparkar approved these changes
lgtm

2022-10-10 13:42 UTC, merged