Updated and Created Readme for desired Topics
commclassroom/roadmaps pull request #228
Opened 2022-10-18 22:41 UTC by Ghat0tkach

## Fixes Issue

Updated README with Roadmap links
Created Blockchain Roadmap readme

## Changes proposed

## Screenshots

## Note to reviewers

2022-10-19 07:29 UTC, siddhant-khisty approved these changes
LGTM.
cc @kaiwalyakoparkar

2022-10-19 15:38 UTC, siddhant-khisty requested changes

2022-10-19 15:38 UTC, siddhant-khisty commented on Mobile-Development/readme.md
> +
Too much whitespace. Please leave only one line between topics

2022-10-19 15:43 UTC, kaiwalyakoparkar requested changes

2022-10-19 15:43 UTC, kaiwalyakoparkar commented on Mobile-Development/readme.md
> +
Remove extra line

2022-10-19 15:43 UTC, kaiwalyakoparkar commented on Mobile-Development/readme.md
> +
Remove above extra 2 line

2022-10-19 15:43 UTC, kaiwalyakoparkar commented on Mobile-Development/readme.md
> +
Remove the additional blank lines

2022-10-19 15:43 UTC, kaiwalyakoparkar commented on Mobile-Development/readme.md
> +
Too many blank lines

2022-10-19 15:43 UTC, kaiwalyakoparkar commented on Mobile-Development/readme.md
> +
Again same, too many blank lines. Remove them

2022-10-19 15:43 UTC, kaiwalyakoparkar commented on Mobile-Development/readme.md
> +
Too many blank lines, kindly remove them

2022-10-19 15:43 UTC, kaiwalyakoparkar commented on Blockchain/readme.md
> +
too many blank lines, please remove them

2022-10-19 15:43 UTC, kaiwalyakoparkar commented on Blockchain/readme.md
> +
Extra blank line please remove it

2022-10-19 15:43 UTC, kaiwalyakoparkar commented on README.md
> +
Additional blank lines, please remove them

2022-10-19 20:01 UTC, siddhant-khisty requested changes
Please add linters where needed

2022-10-19 20:14 UTC, siddhant-khisty approved these changes
Looks good to me. Thanks for your contribution

2022-10-20 12:57 UTC, kaiwalyakoparkar commented on Blockchain/readme.md
>                               <P>[Resource 1](https://dev.to/edge-and-node/the-complete-guide-to-full-stack-web3-development-4g74)</P>
change the `<p>` tag to markdown format

2022-10-20 12:57 UTC, kaiwalyakoparkar commented on Blockchain/readme.md
>                               <P>[1) Waffle](https://ethereum-waffle.readthedocs.io/en/latest/)</P>
change the `<p>` tag to markdown format

2022-10-20 12:57 UTC, kaiwalyakoparkar commented on Blockchain/readme.md
>                              <P>[1)Alchemy](https://www.alchemy.com/)</P>
change the `<p>` tag to markdown format, Alignment issue as well

2022-10-20 12:57 UTC, kaiwalyakoparkar commented on Blockchain/readme.md
> +                             <P>[1) Proof Of Work](https://www.investopedia.com/terms/p/proof-work.asp)</P>
change the `<p>` tag to markdown format

2022-10-20 18:20 UTC, Ghat0tkach commented
I  did the desired changes and apologize for the inconvenience

2022-10-21 18:10 UTC, kaiwalyakoparkar approved these changes
lgtm

2022-10-21 18:10 UTC, merged