Update README.md
commclassroom/roadmaps pull request #238
Opened 2022-10-22 12:56 UTC by shubham1091

there were some links were missing and the blockchain was 2 times so i updated

## Fixes Issue

## Changes proposed

## Screenshots

## Note to reviewers

2022-10-22 17:44 UTC, kaiwalyakoparkar requested changes

2022-10-22 17:44 UTC, kaiwalyakoparkar commented on README.md
> +<!-- <p  align="center"><a href=""><b>Blockchain</b></a></p> -->
Please remove this comment if you are making changes to it.

2022-10-22 17:44 UTC, kaiwalyakoparkar commented on README.md
> +<p  align="center"><a href="https://github.com/commclassroom/roadmaps/blob/main/DevOps/Readme.md"><b>DevOps</b></a></p>
Please use relative linking and not the entire url. Please take a look at this [stack overflow website](https://stackoverflow.com/questions/7653483/github-relative-link-in-markdown-file)

2022-10-23 12:35 UTC, shubham1091 commented
Done👍

2022-10-26 06:59 UTC, shubham1091 commented
Hi do you want me to change anything else in this pr

2022-11-03 18:09 UTC, siddhant-khisty requested changes

2022-11-03 18:09 UTC, siddhant-khisty commented on README.md
> +<p  align="center"><a href="/Frontend-DEVlopment/README.md"><b>Frontend-Development</b></a></p>
the frontend roadmap has a typo which is causing a 404. Please fix it.

2022-11-12 13:53 UTC, siddhant-khisty commented
Closing due to inactivity. And the issue seems to be fixed by a different PR

2022-11-12 13:53 UTC, closed without merging