Updated the readme.md by fixing the hyperlinks
commclassroom/roadmaps pull request #242
Opened 2022-10-22 18:41 UTC by Ghat0tkach

## Fixes Issue
Updated  the missing devops , blockchain and android hyperlinks in readme.md
Changed FullStack from Frontend heading in the Full stack roadmap readme.md

## Changes proposed

## Screenshots

## Note to reviewers

2022-10-22 19:36 UTC, kaiwalyakoparkar requested changes

2022-10-22 19:36 UTC, kaiwalyakoparkar commented on README.md
> +<p  align="center"><a href="Backend-Development#readme"><B>Backend-Development</B></a></p>
Please align the roadmap names to the left. It doesn't look visually aligned with the current readme design

2022-10-22 19:44 UTC, Ghat0tkach commented
shall i change the position of gif image too? or let it be in center?

2022-10-25 18:43 UTC, siddhant-khisty approved these changes
LGTM
cc @kaiwalyakoparkar

2022-11-08 17:57 UTC, kaiwalyakoparkar approved these changes
Lgtm. Sorry for keeping you'll waiting so long

2022-11-08 17:57 UTC, merged