Fix typo
commclassroom/roadmaps pull request #61
Opened 2022-08-07 19:22 UTC by HenokB

2022-08-11 12:53 UTC, kaiwalyakoparkar requested changes

2022-08-11 12:53 UTC, kaiwalyakoparkar commented on README.md
> +This repository contains the list of communities and job portals you can join and apply to. You can also add your current job and other portals and help
I think `You can also add your known job ...` would sound much better than `current`. Also 
- please create an issue and get it assigned to you
- Link this pr to that issue

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-11 19:36 UTC, HenokB reviewed
Typo fix

2022-08-12 09:54 UTC, kaiwalyakoparkar approved these changes
lgtm 🚀 thank you so much for contributing

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-08-12 09:55 UTC, merged